spring.application.name=spring

server.port=8092

# View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.static-path-pattern=/static/**

# Character Encoding
server.tomcat.uri-encoding=UTF-8

# Database MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ltweb2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=M@tkhau2006
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect